import dotenv from 'dotenv';
dotenv.config();

const { PORT, NODE_ENV, MONGO_URI, SENTRY_DSN, DIRECT_URL, DATABASE_URL, SUPABASE_URL, SUPABASE_ANON_API_KEY, EMAIL_USERNAME, EMAIL_APP_PASSWORD, SUPABASE_SERVICE_ROLE_KEY } =
  process.env;

export { PORT, NODE_ENV, MONGO_URI, SENTRY_DSN, DIRECT_URL, DATABASE_URL, SUPABASE_URL, SUPABASE_ANON_API_KEY, EMAIL_USERNAME, EMAIL_APP_PASSWORD, SUPABASE_SERVICE_ROLE_KEY };
